vse:
  docker: &vse
    - image: 'circleci/node:8.11.3'
ansible:
  docker: &ansible
    - image: 'circleci/python'
version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build:
    docker: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker: *ansible
    steps:
      - attach_workspace:
          at: .
      - ansible-playbook/install
      - run:
         command: |
          sudo pip install boto
      - ansible-playbook/playbook:
          playbook: ansible/ec2_deploy.yml
          playbook-options: --user ubuntu --key-file ../test.pem -ssh-common-args '-o StrictHostKeyChecking=no'
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
